export const EVENT = {
    GAME_START: "GAME_START",
    GAME_OVER: "GAME_OVER",
    EXIT_TO_LOBBY: "EXIT_TO_LOBBY",
    GAME_PAUSE: "GAME_PAUSE",
    GAME_RESUME: "GAME_RESUME",


    OPEN_SETTING: "OPEN_SETTING",
    CLOSE_SETTING: "CLOSE_SETTING",

    PLAYER_HIT: "PLAYER_HIT",
    PLAYER_SHOOT: "PLAYER_SHOOT",
    PLAYER_DIE: "PLAYER_DIE",
    ENEMY_DIE: "ENEMY_DIE",
    RESET_GAME: "RESET_GAME",

    TIME_UP: "TIME_UP", 
    TIME_UPDATE: "TIME_UPDATE",

    ENEMY_SPAWN: "ENEMY_SPAWN",
    ENEMY_HIT: "ENEMY_HIT",
    SCORE_UPDATE: "SCORE_UPDATE",
    ENEMY_HP_CHANGED: "ENEMY_HP_CHANGED",
    PLAYER_HP_CHANGED: "PLAYER_HP_CHANGED",
} as const; 