export const EVENT = {
    GAME_START: "GAME_START",
    GAME_OVER: "GAME_OVER",
    EXIT_TO_LOBBY: "EXIT_TO_LOBBY",

    PLAYER_HIT: "PLAYER_HIT",
    PLAYER_DIE: "PLAYER_DIE",
    ENEMY_DIE: "ENEMY_DIE",
    RESET_GAME: "RESET_GAME",

    TIME_UP: "TIME_UP", 
    TIME_UPDATE: "TIME_UPDATE",

    ENEMY_SPAWN: "ENEMY_SPAWN",
    SCORE_UPDATE: "SCORE_UPDATE",
} as const; 